---
  - name: install rpm repo (linux)
    when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
    get_url: url=https://bintray.com/ethankhall/rpm/rpm dest=/etc/yum.repos.d/bintray-ethankhall-rpm.repo mode=0440
    sudo: yes

  - name: install packages (linux)
    when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
    yum: name={{ item }} state=installed
    sudo: yes
    with_items:
      - tmux
      - git
      - vim
      - zsh
      - tree
      - htop
      - ansible
      - npm
      - jq

  - name: tab casks (mac)
    homebrew_tap: tap="{{ item }}" state=present
    when: ansible_distribution == "MacOSX"
    with_items:
      - caskroom/cask
      - caskroom/versions

  - name: install packages (mac)
    when: ansible_distribution == "MacOSX"
    homebrew: name={{ item }} state=installed
    with_items:
      - tmux
      - git
      - vim
      - tig
      - zsh
      - zsh-completions
      - zsh-lovers
      - zsh-syntax-highlighting
      - reattach-to-user-namespace
      - gradle
      - groovy
      - ssh-copy-id
      - watch
      - htop-osx
      - ansible
      - wget
      - dnsmasq
      - npm
      - jq
      - brew-cask

  - name: install cask packages (mac)
    when: ansible_distribution == "MacOSX"
    homebrew_cask: name={{ item }} state=present
    with_items:
      - iterm2
      - vagrant
      - vagrant-manager
      - java7
      - sizeup
      - marked
      - bartender
      - istat-menus
      - vmware-fusion
      - caffeine
      - flux
      - dropbox
      - alfred
